---
- name: create git repos
  hosts: test
  vars:
    repo_one: /opt/repo_one
    repo_two: /opt/repo_two

  tasks:
  - name: setup dirs
    include_tasks: test-pre_setup.yaml
    with_items:
      - "{{ repo_one }}"
      - "{{ repo_two }}"

  - name: create repo_one
    git_init:
      repo: "{{ repo_one }}"

  - name: create file foo in repo_one
    ansible.builtin.lineinfile:
      path: "{{ repo_one }}/foo"
      line: "bar"
      create: true

  - name: add foo file for commit
    git_add:
      repo: "{{ repo_one }}"
      branch: master
      files:
        - "{{ repo_one }}/foo"

  - name: commit foo file to repo_one`
    git_commit:
      repo: "{{ repo_one }}"
      msg: "foo bar commit"
      author: test
      email: test@example.com
    register: result


  - git_clone:
      upstream: "{{ repo_one }}"
      repo: "{{ repo_two }}"

  - ansible.builtin.lineinfile:
      path: "{{ repo_two }}/hello"
      line: "hello world"
      create: true

  - git_add:
      repo: "{{ repo_two }}"
      branch: master
      files:
        - "{{ repo_two }}/hello"

  - git_commit:
      repo: "{{ repo_two }}"
      msg: "test commit"
      author: test
      email: test@example.com
    register: result

  - git_tag:
      repo: "{{ repo_two }}"
      tag: test_tag
      ref: "{{ result.commit }}"
      msg: "create a test tag"
      author: test
      email: test@example.com

#  - git_push:
#      repo: "{{ repo_two }}"
#      tags:
#        - test_tag 

